name: weath_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter 
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.10
  riverpod_annotation: ^2.1.4
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  logger: ^1.4.0
  dio: ^5.3.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3 
  cached_network_image: ^3.2.3
  intl: ^0.18.0
  go_router: ^10.0.0
  internet_connection_checker: ^1.0.0+1
  anim_search_bar: ^2.0.3
  flutter_iconly: ^1.0.2
  syncfusion_flutter_charts: ^21.2.8
  animated_splash_screen: ^1.3.0
  location: ^5.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2 
  custom_lint: ^0.5.2
  freezed: ^2.4.2
  riverpod_generator: ^2.3.1
  riverpod_lint: ^2.0.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  analyzer: ^6.0.0
  requests_inspector: ^3.1.2
  mocktail: ^1.0.0
  
dependency_overrides:
  analyzer: ^5.11.0

flutter: 
  uses-material-design: true
  generate: true # generates flutter localizations 


  assets:
    - assets/
    - assets/images/
 
